// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAapJcAG9qOU-HcWQinK09zxeU8hbKfUQ4',
    appId: '1:21324585118:web:b72730daf64b205b6cc38f',
    messagingSenderId: '21324585118',
    projectId: 'fishbrain-59613',
    authDomain: 'fishbrain-59613.firebaseapp.com',
    storageBucket: 'fishbrain-59613.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN2dapuiKTj0f6qEZFnIVmT_jAdeWlWvw',
    appId: '1:21324585118:android:5f48197be5553e806cc38f',
    messagingSenderId: '21324585118',
    projectId: 'fishbrain-59613',
    storageBucket: 'fishbrain-59613.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtqzLKRlWziJ_JY7APFpVhKDf1et7yRYU',
    appId: '1:21324585118:ios:eb5a5feb68c05a5f6cc38f',
    messagingSenderId: '21324585118',
    projectId: 'fishbrain-59613',
    storageBucket: 'fishbrain-59613.firebasestorage.app',
    iosBundleId: 'com.example.fishface',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtqzLKRlWziJ_JY7APFpVhKDf1et7yRYU',
    appId: '1:21324585118:ios:eb5a5feb68c05a5f6cc38f',
    messagingSenderId: '21324585118',
    projectId: 'fishbrain-59613',
    storageBucket: 'fishbrain-59613.firebasestorage.app',
    iosBundleId: 'com.example.fishface',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAapJcAG9qOU-HcWQinK09zxeU8hbKfUQ4',
    appId: '1:21324585118:web:4d053a9c00d1a8486cc38f',
    messagingSenderId: '21324585118',
    projectId: 'fishbrain-59613',
    authDomain: 'fishbrain-59613.firebaseapp.com',
    storageBucket: 'fishbrain-59613.firebasestorage.app',
  );
}
